consul:
  image: gliderlabs/consul-server
  container_name: consul
  net: "stuffnet"
  command: -bootstrap
  ports:
    - "8500:8500"

app:
  image: local/microstuff
  net: "stuffnet"
  environment:
    CONSUL: http://consul:8500
  ports:
    - "5000:5000"

sessions:
  image: local/microstuff-sessions
  net: "stuffnet"
  environment:
    CONSUL: http://consul:8500
